name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches: 
      - fix/AD-3_dev_workflow
      
  pull_request:
    branches:
      - fix/AD-3_dev_workflow

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POOL_ID: ${{ secrets.POOL_ID }}
          REGION: ${{ secrets.REGION }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh
        shell: bash

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App Designer Website
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        shell: bash

      - name: Tar build files
        run: tar -cvf dist.tar ./dist

      - name: Upload the build output
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.tar

  deploy_to_development:
    name: Deploy Dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download the build output
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Tar extract build files
        run: tar -xf dist.tar

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Deploy
        env:
          STAGE: dev
          SUB_DOMAIN_NAME: app-designer-backend.dev
          REGION:  ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        shell: bash